//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/StefH/AnyOf.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace AnyOfTypes
{
    // Code is based on https://github.com/Informatievlaanderen/hashcode-calculator
    internal static class HashCodeCalculator
    {
        public static int GetHashCode(IEnumerable<object> hashFieldValues)
        {
            const int offset = unchecked((int)2166136261);
            const int prime = 16777619;

            static int HashCodeAggregator(int hashCode, object value) => value == null
                ? (hashCode ^ 0) * prime
                : (hashCode ^ value.GetHashCode()) * prime;

            return hashFieldValues.Aggregate(offset, HashCodeAggregator);
        }
    }
}