// <auto-generated />
using System;
using CodeFirst.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.DataAccess.Migrations.SqlServerDb
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CodeFirst.Models.Models.Actors", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("actor_id")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.HasKey("ActorId")
                        .HasName("actor_pkey");

                    b.ToTable("actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            Birthday = new DateTime(1947, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Arnold",
                            Lastname = "Schwarzenegger"
                        },
                        new
                        {
                            ActorId = 2,
                            Birthday = new DateTime(1946, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Anthony",
                            Lastname = "Daniels"
                        },
                        new
                        {
                            ActorId = 3,
                            Birthday = new DateTime(1942, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Harrison",
                            Lastname = "Ford"
                        },
                        new
                        {
                            ActorId = 4,
                            Birthday = new DateTime(1956, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Carrie",
                            Lastname = "Fisher"
                        },
                        new
                        {
                            ActorId = 5,
                            Birthday = new DateTime(1914, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Alec",
                            Lastname = "Guiness"
                        },
                        new
                        {
                            ActorId = 6,
                            Birthday = new DateTime(1913, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Peter",
                            Lastname = "Cushing"
                        },
                        new
                        {
                            ActorId = 7,
                            Birthday = new DateTime(1944, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "David",
                            Lastname = "Prowse"
                        },
                        new
                        {
                            ActorId = 8,
                            Birthday = new DateTime(1935, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Peter",
                            Lastname = "Mayhew"
                        },
                        new
                        {
                            ActorId = 9,
                            Birthday = new DateTime(1956, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Michael",
                            Lastname = "Biehn"
                        },
                        new
                        {
                            ActorId = 10,
                            Birthday = new DateTime(1956, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Linda",
                            Lastname = "Hamilton"
                        },
                        new
                        {
                            ActorId = 11,
                            Birthday = new DateTime(1950, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Bill",
                            Lastname = "Murray"
                        },
                        new
                        {
                            ActorId = 12,
                            Birthday = new DateTime(1952, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Dan",
                            Lastname = "Aykroyd"
                        },
                        new
                        {
                            ActorId = 13,
                            Birthday = new DateTime(1949, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Sigourney",
                            Lastname = "Weaver"
                        },
                        new
                        {
                            ActorId = 14,
                            Birthday = new DateTime(1943, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Robert",
                            Lastname = "De Niro"
                        },
                        new
                        {
                            ActorId = 15,
                            Birthday = new DateTime(1962, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Jodie",
                            Lastname = "Foster"
                        },
                        new
                        {
                            ActorId = 16,
                            Birthday = new DateTime(1939, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Harvey",
                            Lastname = "Keitel"
                        },
                        new
                        {
                            ActorId = 17,
                            Birthday = new DateTime(1950, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Cybill",
                            Lastname = "Shepherd"
                        },
                        new
                        {
                            ActorId = 18,
                            Birthday = new DateTime(1949, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Tom",
                            Lastname = "Berenger"
                        },
                        new
                        {
                            ActorId = 19,
                            Birthday = new DateTime(1955, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Willem",
                            Lastname = "Dafoe"
                        },
                        new
                        {
                            ActorId = 20,
                            Birthday = new DateTime(1965, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Charlie",
                            Lastname = "Sheen"
                        },
                        new
                        {
                            ActorId = 21,
                            Birthday = new DateTime(1942, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Harrison",
                            Lastname = "Ford"
                        },
                        new
                        {
                            ActorId = 22,
                            Birthday = new DateTime(1966, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Emmanuelle",
                            Lastname = "Seigner"
                        },
                        new
                        {
                            ActorId = 23,
                            Birthday = new DateTime(1948, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Jean",
                            Lastname = "Reno"
                        },
                        new
                        {
                            ActorId = 24,
                            Birthday = new DateTime(1948, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Billy",
                            Lastname = "Crystal"
                        },
                        new
                        {
                            ActorId = 25,
                            Birthday = new DateTime(1963, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Lisa",
                            Lastname = "Kudrow"
                        },
                        new
                        {
                            ActorId = 26,
                            Birthday = new DateTime(1958, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Gary",
                            Lastname = "Oldman"
                        },
                        new
                        {
                            ActorId = 27,
                            Birthday = new DateTime(1981, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Natalie",
                            Lastname = "Portman"
                        },
                        new
                        {
                            ActorId = 28,
                            Birthday = new DateTime(1962, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Tom",
                            Lastname = "Cruise"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Clients", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_id")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.HasKey("ClientId")
                        .HasName("client_pkey");

                    b.ToTable("clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Birthday = new DateTime(1954, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Hank",
                            Lastname = "Hill"
                        },
                        new
                        {
                            ClientId = 2,
                            Birthday = new DateTime(2011, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Brian",
                            Lastname = "Griffin"
                        },
                        new
                        {
                            ClientId = 3,
                            Birthday = new DateTime(1989, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Gary",
                            Lastname = "Goodspeed"
                        },
                        new
                        {
                            ClientId = 4,
                            Birthday = new DateTime(1977, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Bob",
                            Lastname = "Belcher"
                        },
                        new
                        {
                            ClientId = 5,
                            Birthday = new DateTime(2012, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Lisa",
                            Lastname = "Simpson"
                        },
                        new
                        {
                            ClientId = 6,
                            Birthday = new DateTime(1965, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firstname = "Rick",
                            Lastname = "Sanchez"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Copies", b =>
                {
                    b.Property<int>("CopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("copy_id")
                        .UseIdentityColumn();

                    b.Property<bool>("Available")
                        .HasColumnType("bit")
                        .HasColumnName("available");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.HasKey("CopyId")
                        .HasName("copies_pkey");

                    b.HasIndex("MovieId");

                    b.ToTable("copies");

                    b.HasData(
                        new
                        {
                            CopyId = 1,
                            Available = true,
                            MovieId = 1
                        },
                        new
                        {
                            CopyId = 2,
                            Available = false,
                            MovieId = 1
                        },
                        new
                        {
                            CopyId = 3,
                            Available = true,
                            MovieId = 2
                        },
                        new
                        {
                            CopyId = 4,
                            Available = true,
                            MovieId = 3
                        },
                        new
                        {
                            CopyId = 5,
                            Available = false,
                            MovieId = 3
                        },
                        new
                        {
                            CopyId = 6,
                            Available = true,
                            MovieId = 3
                        },
                        new
                        {
                            CopyId = 7,
                            Available = true,
                            MovieId = 4
                        },
                        new
                        {
                            CopyId = 8,
                            Available = false,
                            MovieId = 5
                        },
                        new
                        {
                            CopyId = 9,
                            Available = true,
                            MovieId = 6
                        },
                        new
                        {
                            CopyId = 10,
                            Available = false,
                            MovieId = 6
                        },
                        new
                        {
                            CopyId = 11,
                            Available = true,
                            MovieId = 6
                        },
                        new
                        {
                            CopyId = 12,
                            Available = true,
                            MovieId = 7
                        },
                        new
                        {
                            CopyId = 13,
                            Available = true,
                            MovieId = 7
                        },
                        new
                        {
                            CopyId = 14,
                            Available = false,
                            MovieId = 8
                        },
                        new
                        {
                            CopyId = 15,
                            Available = true,
                            MovieId = 9
                        },
                        new
                        {
                            CopyId = 16,
                            Available = true,
                            MovieId = 10
                        },
                        new
                        {
                            CopyId = 17,
                            Available = false,
                            MovieId = 10
                        },
                        new
                        {
                            CopyId = 18,
                            Available = true,
                            MovieId = 10
                        },
                        new
                        {
                            CopyId = 19,
                            Available = true,
                            MovieId = 10
                        },
                        new
                        {
                            CopyId = 20,
                            Available = true,
                            MovieId = 10
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Employees", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<float?>("Salary")
                        .HasColumnType("real")
                        .HasColumnName("salary");

                    b.HasKey("EmployeeId")
                        .HasName("employee_id");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            City = "New York",
                            Firstname = "John",
                            Lastname = "Smith",
                            Salary = 150f
                        },
                        new
                        {
                            EmployeeId = 2,
                            City = "New York",
                            Firstname = "Ben",
                            Lastname = "Johnson",
                            Salary = 250f
                        },
                        new
                        {
                            EmployeeId = 3,
                            City = "New Orleans",
                            Firstname = "Louis",
                            Lastname = "Armstrong",
                            Salary = 75f
                        },
                        new
                        {
                            EmployeeId = 4,
                            City = "London",
                            Firstname = "John",
                            Lastname = "Lennon",
                            Salary = 300f
                        },
                        new
                        {
                            EmployeeId = 5,
                            City = "London",
                            Firstname = "Peter",
                            Lastname = "Gabriel",
                            Salary = 150f
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Movies", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("movie_id")
                        .UseIdentityColumn();

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int")
                        .HasColumnName("age_restriction");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("MovieId")
                        .HasName("movies_pkey");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            AgeRestriction = 12,
                            Price = 10f,
                            Title = "Star Wars Episode IV: A New Hope",
                            Year = 1979
                        },
                        new
                        {
                            MovieId = 2,
                            AgeRestriction = 12,
                            Price = 5.5f,
                            Title = "Ghostbusters",
                            Year = 1984
                        },
                        new
                        {
                            MovieId = 3,
                            AgeRestriction = 15,
                            Price = 8.5f,
                            Title = "Terminator",
                            Year = 1984
                        },
                        new
                        {
                            MovieId = 4,
                            AgeRestriction = 17,
                            Price = 5f,
                            Title = "Taxi Driver",
                            Year = 1976
                        },
                        new
                        {
                            MovieId = 5,
                            AgeRestriction = 18,
                            Price = 5f,
                            Title = "Platoon",
                            Year = 1986
                        },
                        new
                        {
                            MovieId = 6,
                            AgeRestriction = 15,
                            Price = 8.5f,
                            Title = "Frantic",
                            Year = 1988
                        },
                        new
                        {
                            MovieId = 7,
                            AgeRestriction = 13,
                            Price = 9.5f,
                            Title = "Ronin",
                            Year = 1998
                        },
                        new
                        {
                            MovieId = 8,
                            AgeRestriction = 16,
                            Price = 10.5f,
                            Title = "Analyze This",
                            Year = 1999
                        },
                        new
                        {
                            MovieId = 9,
                            AgeRestriction = 16,
                            Price = 8.5f,
                            Title = "Leon: the Professional",
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 10,
                            AgeRestriction = 13,
                            Price = 8.5f,
                            Title = "Mission Impossible",
                            Year = 1996
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Rentals", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<int>("CopyId")
                        .HasColumnType("int")
                        .HasColumnName("copy_id");

                    b.Property<DateTime?>("DateOfRental")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_rental");

                    b.Property<DateTime?>("DateOfReturn")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_return");

                    b.HasKey("ClientId", "CopyId")
                        .HasName("rentals_pkey");

                    b.HasIndex("CopyId");

                    b.ToTable("rentals");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            CopyId = 1,
                            DateOfRental = new DateTime(2005, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 1,
                            CopyId = 6,
                            DateOfRental = new DateTime(2005, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 2,
                            CopyId = 3,
                            DateOfRental = new DateTime(2005, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 2,
                            CopyId = 5,
                            DateOfRental = new DateTime(2005, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 2,
                            CopyId = 7,
                            DateOfRental = new DateTime(2005, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 3,
                            CopyId = 12,
                            DateOfRental = new DateTime(2005, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 3,
                            CopyId = 20,
                            DateOfRental = new DateTime(2005, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 3,
                            CopyId = 3,
                            DateOfRental = new DateTime(2005, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 3,
                            CopyId = 7,
                            DateOfRental = new DateTime(2005, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 4,
                            CopyId = 13,
                            DateOfRental = new DateTime(2005, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 5,
                            CopyId = 11,
                            DateOfRental = new DateTime(2005, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 6,
                            CopyId = 1,
                            DateOfRental = new DateTime(2005, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 6,
                            CopyId = 7,
                            DateOfRental = new DateTime(2005, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClientId = 6,
                            CopyId = 19,
                            DateOfRental = new DateTime(2005, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfReturn = new DateTime(2005, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Starring", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int")
                        .HasColumnName("actor_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("starring");

                    b.HasData(
                        new
                        {
                            ActorId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 3,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 4,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 5,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 6,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 7,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 8,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 1,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 9,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 10,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 11,
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 12,
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 13,
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 14,
                            MovieId = 4
                        },
                        new
                        {
                            ActorId = 15,
                            MovieId = 4
                        },
                        new
                        {
                            ActorId = 16,
                            MovieId = 4
                        },
                        new
                        {
                            ActorId = 17,
                            MovieId = 4
                        },
                        new
                        {
                            ActorId = 18,
                            MovieId = 5
                        },
                        new
                        {
                            ActorId = 19,
                            MovieId = 5
                        },
                        new
                        {
                            ActorId = 20,
                            MovieId = 5
                        },
                        new
                        {
                            ActorId = 21,
                            MovieId = 6
                        },
                        new
                        {
                            ActorId = 22,
                            MovieId = 6
                        },
                        new
                        {
                            ActorId = 14,
                            MovieId = 7
                        },
                        new
                        {
                            ActorId = 23,
                            MovieId = 7
                        },
                        new
                        {
                            ActorId = 14,
                            MovieId = 8
                        },
                        new
                        {
                            ActorId = 24,
                            MovieId = 8
                        },
                        new
                        {
                            ActorId = 25,
                            MovieId = 8
                        },
                        new
                        {
                            ActorId = 23,
                            MovieId = 9
                        },
                        new
                        {
                            ActorId = 27,
                            MovieId = 9
                        },
                        new
                        {
                            ActorId = 23,
                            MovieId = 10
                        },
                        new
                        {
                            ActorId = 28,
                            MovieId = 10
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Copies", b =>
                {
                    b.HasOne("CodeFirst.Models.Models.Movies", "Movie")
                        .WithMany("Copies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Rentals", b =>
                {
                    b.HasOne("CodeFirst.Models.Models.Clients", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Models.Copies", "Copy")
                        .WithMany("Rentals")
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Copy");
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Starring", b =>
                {
                    b.HasOne("CodeFirst.Models.Models.Actors", "Actor")
                        .WithMany("Starring")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst.Models.Models.Movies", "Movie")
                        .WithMany("Starring")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Actors", b =>
                {
                    b.Navigation("Starring");
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Clients", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Copies", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CodeFirst.Models.Models.Movies", b =>
                {
                    b.Navigation("Copies");

                    b.Navigation("Starring");
                });
#pragma warning restore 612, 618
        }
    }
}
